app = "pori"
primary_region = "iad"  # Change to your preferred region

[build]
dockerfile = "Dockerfile"

[env]
NODE_ENV = "production"
PORT = "8080"
HOST = "0.0.0.0"
# All sensitive secrets are set via fly secrets
# Non-sensitive configuration can be set here
LOG_LEVEL = "info"
METRICS_ENABLED = "true"
COMPRESSION_ENABLED = "true"
# Force console output for Fly.io log collection
FORCE_CONSOLE_OUTPUT = "true"
  
[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

# Unified deployment - all services in one container
[processes]
  app = "/app/init.sh --supervisor"

# VM Configuration for unified deployment
[[vm]]
  memory = "2048mb"  # More memory for MongoDB + Redis + App
  cpu_kind = "shared"
  cpus = 2

# Persistent volume for MongoDB and Redis data
[mounts]
  source = "proxy_data"
  destination = "/data"

# Deploy configuration
[deploy]
  strategy = "immediate"
  release_command = "echo 'Starting unified proxy server deployment...'"