name: Deploy to Ubuntu Server

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Add server to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        
    - name: Create production environment file from secrets
      run: |
        cat > docker/prod/.env << EOF
        # ===========================================
        # PRODUCTION ENVIRONMENT CONFIGURATION
        # ===========================================

        # Server Configuration
        HOST=0.0.0.0
        PORT=8080
        NODE_ENV=production

        # Security - CHANGE THESE TO STRONG SECRETS!
        # Generate with: node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
        AUTH_TOKEN=${{ secrets.AUTH_TOKEN }}
        HEX_ENCRYPTION_KEY=${{ secrets.HEX_ENCRYPTION_KEY }}

        # Domain Configuration
        DOMAIN=${{ secrets.DOMAIN }}
        SSL_EMAIL=${{ secrets.SSL_EMAIL }}

        # CORS Configuration
        ALLOWED_ORIGINS=*

        # MongoDB Configuration - Production with auth
        MONGO_ROOT_PASSWORD=${{ secrets.MONGO_ROOT_PASSWORD }}
        MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}
        MONGODB_URI=mongodb://proxy_user:\${MONGO_PASSWORD}@mongo:27017/proxy?authSource=proxy
        MONGO_URI=mongodb://proxy_user:\${MONGO_PASSWORD}@mongo:27017/proxy?authSource=proxy
        MONGO_MAX_POOL_SIZE=20
        MONGO_SERVER_SELECTION_TIMEOUT=5000
        MONGO_SOCKET_TIMEOUT=45000
        MONGO_OPTIONS_STRING=retryWrites=true&w=majority

        # Redis Configuration - Production with auth
        REDIS_HOST=redis
        REDIS_PORT=6379
        REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
        REDIS_URL=redis://:\${REDIS_PASSWORD}@redis:6379
        REDIS_DB=0
        REDIS_MAX_RETRIES=3

        # Proxy Configuration
        PROXY_TIMEOUT=30000
        MAX_REQUEST_SIZE=10mb
        COMPRESSION_ENABLED=true

        # Metrics Configuration
        METRICS_ENABLED=true
        METRICS_RETENTION_DAYS=30

        # WebSocket Configuration
        WS_MAX_COMPRESSED_SIZE=65536
        WS_MAX_BACKPRESSURE=65536
        WS_PING_INTERVAL=30000

        # Logging Configuration
        LOG_LEVEL=info
        LOG_FORMAT=json
        FORCE_CONSOLE_OUTPUT=false

        # Performance Configuration
        MAX_CONCURRENT_REQUESTS=2000
        REQUEST_RATE_LIMIT=200
        DEVICE_CACHE_TTL=7200

        # Security Headers & Rate Limiting
        CORS_ORIGINS=https://${{ secrets.DOMAIN }},https://www.${{ secrets.DOMAIN }}
        RATE_LIMIT_WINDOW=900000
        RATE_LIMIT_MAX_REQUESTS=200
        MAX_CONNECTIONS=2000

        # Production Configuration
        DEBUG_MODE=false
        MOCK_RESPONSES=false
        SIMULATE_LATENCY=0

        # SSL Configuration
        SSL_CERT_PATH=/etc/nginx/ssl/cert.pem
        SSL_KEY_PATH=/etc/nginx/ssl/key.pem
        EOF
        
    - name: Copy production environment file to server
      run: |
        scp docker/prod/.env ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }}:~/apps/Proxy/docker/prod/.env
        
    - name: Deploy to production server
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          # Navigate to the apps directory
          cd apps/Proxy
          
          # Pull latest changes
          git pull origin main
          
          # Navigate to docker directory
          cd docker
          
          # Stop existing containers
          make prod-stop || true
          
          # Start the production application
          make prod-start
        EOF
        
    - name: Setup SSL certificates (if domain configured)
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd apps/Proxy/docker
          # Only setup SSL if domain is configured and not localhost
          if [ "${{ secrets.DOMAIN }}" != "" ] && [ "${{ secrets.DOMAIN }}" != "localhost" ]; then
            echo "Setting up SSL certificates for ${{ secrets.DOMAIN }}..."
            ENV=prod make ssl-setup || echo "SSL setup failed or already configured"
            sleep 10
            make prod-restart
          else
            echo "No domain configured or localhost detected, skipping SSL setup"
          fi
        EOF
        
    - name: Verify production deployment
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd apps/Proxy/docker
          echo "Waiting for production services to start..."
          sleep 30
          make prod-status
        EOF
